export const STATES_TAXES = [
  { state: "Alabama", tax: 4 },
  { state: "Alaska", tax: 0 },
  { state: "Arizona", tax: 5.6 },
  { state: "Arkansas", tax: 6.5 },
  { state: "California", tax: 7.25 },
  { state: "Colorado", tax: 2.9 },
  { state: "Connecticut", tax: 6.35 },
  { state: "Delaware", tax: 0 },
  { state: "District of Columbia", tax: 6 },
  { state: "Florida", tax: 6 },
  { state: "Georgia", tax: 4 },
  { state: "Hawaii", tax: 4.166 },
  { state: "Idaho", tax: 6 },
  { state: "Illinois", tax: 6.25 },
  { state: "Indiana", tax: 7 },
  { state: "Iowa", tax: 6 },
  { state: "Kansas", tax: 6.5 },
  { state: "Kentucky", tax: 6 },
  { state: "Louisiana", tax: 5 },
  { state: "Maine", tax: 5.5 },
  { state: "Maryland", tax: 6 },
  { state: "Massachusetts", tax: 6.25 },
  { state: "Michigan", tax: 6 },
  { state: "Minnesota", tax: 6.875 },
  { state: "Mississippi", tax: 7 },
  { state: "Missouri", tax: 4.225 },
  { state: "Montana", tax: 0 },
  { state: "Nebraska", tax: 5.5 },
  { state: "Nevada", tax: 6.85 },
  { state: "New Hampshire", tax: 0 },
  { state: "New Jersey", tax: 6.625 },
  { state: "New Mexico", tax: 5.125 },
  { state: "New York", tax: 4 },
  { state: "North Carolina", tax: 4.75 },
  { state: "North Dakota", tax: 5 },
  { state: "Ohio", tax: 5.75 },
  { state: "Oklahoma", tax: 4.5 },
  { state: "Oregon", tax: 0 },
  { state: "Pennsylvania", tax: 6 },
  { state: "Rhode Island", tax: 7 },
  { state: "South Carolina", tax: 6 },
  { state: "South Dakota", tax: 4 },
  { state: "Tennessee", tax: 7 },
  { state: "Texas", tax: 6.25 },
  { state: "Utah", tax: 5.95 },
  { state: "Vermont", tax: 6 },
  { state: "Virginia", tax: 5.3 },
  { state: "Washington", tax: 6.5 },
  { state: "West Virginia", tax: 6 },
  { state: "Wisconsin", tax: 5 },
  { state: "Wyoming", tax: 4 },
];
