export const ADD_ITEM_TO_WISHLIST = "ADD_ITEM_TO_WISHLIST";
export const ADD_ALL_ITEMS_TO_WISHLIST = "ADD_ALL_ITEMS_TO_WISHLIST";
export const REMOVE_ITEM_FROM_WISHLIST = "REMOVE_ITEM_FROM_WISHLIST";
export const REMOVE_ALL_ITEMS_FROM_WISHLIST = "REMOVE_ALL_ITEMS_FROM_WISHLIST";