export const TOGGLE_SHOPPING_CART_MODAL = "TOGGLE_SHOPPING_CART_MODAL";
export const TOGGLE_WISHLIST_MODAL = "TOGGLE_WISHLIST_MODAL";
export const OPEN_SHOPPING_CART_MODAL = "OPEN_SHOPPING_CART";
export const OPEN_WISHLIST_MODAL = "OPEN_WISHLIST_MODAL";
export const CLOSE_SHOPPING_CART_MODAL = "CLOSE_SHOPPING_CART";
export const CLOSE_WISHLIST_MODAL = "CLOSE_WISHLIST_MODAL";
export const CLOSE_SHOPPING_CART_AND_WISHLIST_MODALS = "CLOSE_SHOPPING_CART_AND_WISHLIST_MODALS";