import { ModalsState } from "./modalTypes";

export const TOGGLE_SHOPPING_CART_MODAL = "TOGGLE_SHOPPING_CART_MODAL";
export const TOGGLE_WISHLIST_MODAL = "TOGGLE_WISHLIST_MODAL";

export const OPEN_SHOPPING_CART_MODAL = "OPEN_SHOPPING_CART";
export const OPEN_WISHLIST_MODAL = "OPEN_WISHLIST_MODAL";

export const CLOSE_SHOPPING_CART_MODAL = "CLOSE_SHOPPING_CART";
export const CLOSE_WISHLIST_MODAL = "CLOSE_WISHLIST_MODAL";
export const CLOSE_SHOPPING_CART_AND_WISHLIST_MODALS = "CLOSE_SHOPPING_CART_AND_WISHLIST_MODALS";

export const START_EDIT_WISHLIST_MODAL = "START_EDIT_WISHLIST_MODAL";
export const START_EDIT_SHOPPING_CART_MODAL = "START_EDIT_SHOPPING_CART_MODAL";
export const STOP_EDIT_WISHLIST_MODAL = "STOP_EDIT_WISHLIST_MODAL";
export const STOP_EDIT_SHOPPING_CART_MODAL = "STOP_EDIT_SHOPPING_CART_MODAL";

export const CLOSE_WISHLIST_OPEN_SHOPPING_CART = "CLOSE_WISHLIST_OPEN_SHOPPING_CART";


export const modalsInitState: ModalsState = {
  wishlist: {
    isOpen: false,
    isEditting: false,
  },
  shoppingCart: {
    isOpen: false,
    isEditting: false,
  }
}